### PR TITLE
Resolve merge conflicts

### PR DESCRIPTION
**Pull request by rammba**
I saw there are few merge conflicts so this it the first thing I want to fix.

### CODE REVIEW

**Comment by lxmarinkovic** [comment]
@rammba thanks for the effort; I'll try to review it reasonably soon :D

**Comment by rammba** [comment]
The reason why pipeline fails is the change on parent repo, which is not yet propagated here.

**Review by lxmarinkovic — COMMENTED** [review]
LGTM :D

**Comment by lxmarinkovic** [comment]
> The reason why pipeline fails is the change on parent repo, which is not yet propagated here.

I think I fixed that now :D

**Comment by rammba** [comment]
Great, we have working version @ [sr-react-dev.vercel.app](https://sr-react-dev.vercel.app/)

**Pull request merged**
